// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "description": "Find all events",
                "tags": [
                    "event"
                ],
                "summary": "Find all events",
                "responses": {}
            },
            "post": {
                "description": "Create a new event",
                "tags": [
                    "event"
                ],
                "summary": "Create a new event",
                "responses": {}
            }
        },
        "/events/{id}": {
            "get": {
                "description": "Find an event",
                "tags": [
                    "event"
                ],
                "summary": "Find an event",
                "responses": {}
            },
            "put": {
                "description": "Update an event",
                "tags": [
                    "event"
                ],
                "summary": "Update an event",
                "responses": {}
            },
            "delete": {
                "description": "Delete an event",
                "tags": [
                    "event"
                ],
                "summary": "Delete an event",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "GoEvents API",
	Description:      "GoEvents API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
