# version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goevents
      MYSQL_USER: goevents
      MYSQL_PASSWORD: goevents
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
