// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"goevents/internal/infrastructure/repositories/event"
	"goevents/internal/interface/delivery/http/controllers"
	"goevents/internal/usecases"
)

// Injectors from wire.go:

func InitializeEventController(db *sql.DB) *controllers.EventController {
	eventRepository := event.NewEventRepositoryMySQL(db)
	eventUsecase := usecases.NewEventUsecase(eventRepository)
	eventController := controllers.NewEventController(eventUsecase)
	return eventController
}
